### ISSUE TITLE
Team Tracking

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#522]
Rebuilding the legacy feature for tracking teams.

## Operations
- [x] Create team with members
- [x] List teams
- [x] Update teams
  - [x] Change name
  - [x] Change members
- [x] Delete team

## UX
- [x] Create a new team
- [x] List of teams
- [ ] Bowl with a team
- [x] Delete a team
- [x] Update a team
- [ ] Team statistics
