### ISSUE TITLE
Team Tracking support for iOS

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#542]
Aiming for feature parity with Android:

## Operations
- [ ] Create team with members
- [ ] List teams
- [ ] Update teams
  - [ ] Change name
- [ ] Archive team
- [ ] Add existing series to a team

## UX
- [ ] Create a new team
- [ ] List of teams
- [ ] Bowl with a team
- [ ] Delete a team
- [ ] Update a team
- [ ] Team statistics

**Comment by autoreleasefool** [comment]
Team DB support added in #556
